spring:
  application:
    name: reservation-server

  datasource:
    url: jdbc:mysql://localhost:13306/reservation_db?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: client
    password: password123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
       format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations: classpath:/sql/data.sql

  data:
    redis:
      host: localhost
      port: 16379

resilience4j.circuitbreaker:
  instances:
    booking:
      registerHealthIndicator: true
      slidingWindowSize: 20             # 최근 20개의 요청을 기준으로 판단
      failureRateThreshold: 50          # 실패율이 50% 이상이면 서킷 오픈
      waitDurationInOpenState: 10s      # 서킷이 열린 후 10초 동안은 무조건 차단
      permittedNumberOfCallsInHalfOpenState: 5 # 10초 후 5개만 흘려보내서 복구 확인
